# TODO this action takes only into consideration the last complete job, and not the look deeper if the name does not match.
# It should look recursively till a max depth in completed jobs for the artifact name asked
name: 'get_workflow_id'
description: 'TODO'

inputs:

  workflow_source:
    description: 'Name of the workflow to look for'
    required: true

  artifact_name:
    description: 'Name of the artifact to look for'
    required: true

  workflow_source_repository:
    description: 'Name of the repository to look for the job id [this repository]'
    required: false
    default: '$GITHUB_REPOSITORY'

  id_job_result:
    description: 'Name of the env variable to store the job id'
    required: false
    default: 'job_id'

  job_status:
    description: 'Workspace to source where dependencies are'
    required: false
    default: 'completed'

  # Windows argument
  # Pass argument {{ secrets.GITHUB_TOKEN }} from workflow
  secret_token:
    description: 'Secret token to authenticate the WebRequest so it not get a rate limit error.'
    required: false
    default: ''

runs:
  using: composite
  steps:

    - name: Install in ubuntu
      uses: jparisu/eProsima-CI/ubuntu/get_workflow_id@main
      if: runner.os == 'Linux'
      with:
        workflow_source: ${{ inputs.workflow_source }}
        artifact_name: '${{ inputs.artifact_name }}'
        workflow_source_repository: ${{ inputs.workflow_source_repository }}
        id_job_result: ${{ inputs.id_job_result }}
        job_status: ${{ inputs.job_status }}
        secret_token: ${{ inputs.secret_token }}

    - name: Install in windows
      uses: jparisu/eProsima-CI/windows/get_workflow_id@main
      if: runner.os == 'Windows'
      with:
        workflow_source: ${{ inputs.workflow_source }}
        artifact_name: '${{ inputs.artifact_name }}'
        workflow_source_repository: ${{ inputs.workflow_source_repository }}
        id_job_result: ${{ inputs.id_job_result }}
        job_status: ${{ inputs.job_status }}
        secret_token: ${{ inputs.secret_token }}
