# TODO

name: build_fastdds

on:

  workflow_dispatch:

    inputs:

      built_configuration_branch:
        description: 'Branch or tag of eProsima-CI repository to get .repos and colcon.meta from that will be executed'
        required: false
        default: 'main'

      artifacts_name_postfix:
        description: 'Addition to artifacts name creation (use non default postfix when creating artifacts with specific arguments).'
        required: false
        default: '_manual'

  schedule:

    # Every night at 00:00
    - cron: '0 0 * * *'

jobs:

  build_fastdds:

    runs-on: ${{ matrix.ubuntu-version }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
        cmake-config:
          - Release
          - Debug
        exclude:
          # exclude ubuntu in debug
          - platform: ubuntu-20.04
            cmake-config: Debug
          - platform: ubuntu-22.04
            cmake-config: Debug

    steps:

      - name: Sync this repository
        uses: actions/checkout@v3
        with:
          path: src/eprosima-CI

      - name: Get colcon.meta and .repos files to build fastdds
        uses: jparisu/eProsima-CI/ubuntu/get_configurations_from_repo@main
        env:
          DEFAULT_CONFIGURATION_BRANCH: 'main'
        with:
          source_repository_branch: ${{ inputs.built_configuration_branch || env.DEFAULT_CONFIGURATION_BRANCH }}
          colcon_meta_file_path: .github/workflows/configurations/fastdds/colcon.meta
          repos_file_path: .github/workflows/configurations/fastdds/dependencies.repos

      - name: Build Fast DDS and generate artifact
        uses: jparisu/eProsima-CI/ubuntu/generate_dependency@main
        env:
          DEFAULT_ARTIFACT_POSTFIX: '_nightly'
        with:
          vcs_repos_file: dependencies.repos
          artifact_name: built_fastdds_${{ matrix.ubuntu-version }}${{ inputs.artifacts_name_postfix || env.DEFAULT_ARTIFACT_POSTFIX }}
          colcon_meta_file: colcon.meta
